---
version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /apps/api
      - /apps/web
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
        applies-to: version-updates
        group-by: dependency-name
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        applies-to: version-updates
        group-by: dependency-name
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      workflow-actions:
        patterns:
          - '*'
        applies-to: version-updates
        update-types:
          - minor
          - patch
