packages:
  - .
  - apps/*

allowBuilds:
  '@scarf/scarf': false
  unrs-resolver: false
  nx: true

minimumReleaseAgeExclude:
  - '@nestjs/common@11.2.3'
  - '@nestjs/core@11.2.3'
  - '@nestjs/platform-express@11.2.3'
  - '@nestjs/testing@11.2.3'
